"""Import all move generators to register them with the dispatcher."""

# Standard pieces
from game3d.movement.piecemoves.pawnmoves import pawn_move_dispatcher
from game3d.movement.piecemoves.knightmoves import knight_move_dispatcher
from game3d.movement.piecemoves.bishopmoves import bishop_move_dispatcher
from game3d.movement.piecemoves.rookmoves import rook_move_dispatcher
from game3d.movement.piecemoves.queenmoves import queen_move_dispatcher
from game3d.movement.piecemoves.kingmoves import king_move_dispatcher

# Special pieces
from game3d.movement.piecemoves.knight32moves import knight32_move_dispatcher
from game3d.movement.piecemoves.knight31moves import knight31_move_dispatcher
from game3d.movement.piecemoves.trigonalbishopmoves import trigonal_bishop_move_dispatcher
from game3d.movement.piecemoves.hivemoves import hive_move_dispatcher
from game3d.movement.piecemoves.orbitalmoves import orbital_move_dispatcher
from game3d.movement.piecemoves.nebulamoves import nebula_move_dispatcher
from game3d.movement.piecemoves.echomoves import echo_move_dispatcher
from game3d.movement.piecemoves.panelmoves import panel_move_dispatcher
from game3d.movement.piecemoves.edgerookmoves import edgerook_move_dispatcher
from game3d.movement.piecemoves.xyqueenmoves import xy_queen_move_dispatcher
from game3d.movement.piecemoves.xzqueenmoves import xz_queen_move_dispatcher
from game3d.movement.piecemoves.yzqueenmoves import yz_queen_move_dispatcher
from game3d.movement.piecemoves.vectorslidermoves import vectorslider_move_dispatcher
from game3d.movement.piecemoves.priestmoves import priest_move_dispatcher
from game3d.movement.piecemoves.spiralmoves import spiral_move_dispatcher
from game3d.movement.piecemoves.trailblazermoves import trailblazer_move_dispatcher
from game3d.movement.piecemoves.xzzigzagmoves import xz_zigzag_move_dispatcher
from game3d.movement.piecemoves.yzzigzagmoves import yz_zigzag_move_dispatcher
from game3d.movement.piecemoves.faceconemoves import face_cone_move_dispatcher
from game3d.movement.piecemoves.freezermoves import freezer_move_dispatcher
from game3d.movement.piecemoves.wallmoves import wall_move_dispatcher
from game3d.movement.piecemoves.archermoves import archer_move_dispatcher
from game3d.movement.piecemoves.bombmoves import bomb_move_dispatcher
from game3d.movement.piecemoves.speedermoves import speeder_move_dispatcher
from game3d.movement.piecemoves.slowermoves import slower_move_dispatcher
from game3d.movement.piecemoves.geomancermoves import geomancer_move_dispatcher
from game3d.movement.piecemoves.swappermoves import swapper_move_dispatcher
from game3d.movement.piecemoves.blackholemoves import blackhole_move_dispatcher
from game3d.movement.piecemoves.whiteholemoves import whitehole_move_dispatcher
from game3d.movement.piecemoves.armourmoves import armour_move_dispatcher
from game3d.movement.piecemoves.reflectingbishopmoves import reflecting_bishop_move_dispatcher
from game3d.movement.piecemoves.mirrorteleportmoves import mirror_teleport_move_dispatcher
from game3d.movement.piecemoves.networkteleportmoves import network_teleport_move_dispatcher
from game3d.movement.piecemoves.friendlyswapmoves import friendly_swap_move_dispatcher
from game3d.movement.piecemoves.pawnfrontteleportmoves import pawn_front_teleport_move_dispatcher
